In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/Users/irfankhan/Downloads/Mumbai_housing_data.csv')
df.head(15)

,price,Address,area,latitude,longitude,Bedrooms,Bathrooms,Balcony,Status,neworold,parking,Furnished_status,Lift,Landmarks,type_of_building,desc,Price_sqft
0,22400000.0,"Chembur, Mumbai - Harbour Line, Maharashtra",629.0,19.032800,72.896357,2.0,2.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Right fr...,35612.082671
1,35000000.0,"Chembur, Mumbai - Harbour Line, Maharashtra",974.0,19.032800,72.896357,3.0,2.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Right fr...,35934.291581
2,31700000.0,"Ghatkopar East, Mumbai - Central Line, Maharas...",968.0,19.085600,72.909277,3.0,3.0,NaN,Under Construction,New Property,1.0,NaN,2.0,NaN,Flat,\n \n \n...,32747.933884
3,18700000.0,"Plot Number 283, Road Number 3, Jawahar Nagar,...",629.0,19.155756,72.846862,2.0,2.0,2.0,Ready to Move,New Property,1.0,NaN,3.0,Laxmi Callista,Flat,\n\n\n Welcome ...,29729.729730
4,13500000.0,"malad east, Malad East, Mumbai - North Mumbai,...",1090.0,19.177555,72.849887,2.0,2.0,NaN,NaN,New Property,1.0,Unfurnished,2.0,near uper govind nagar,Flat,\n \n \n...,12385.321101
5,13000000.0,"Bhandup, Mumbai, Bhandup, Mumbai - Central Lin...",630.0,19.148058,72.937725,2.0,2.0,NaN,NaN,New Property,1.0,Unfurnished,2.0,LBS road bhandup west 7 min walking from station,Flat,\n\n\n Located ...,20634.920635
6,20700000.0,"Siddharth Nagar, Goregaon West, Mumbai, Gorega...",1188.0,19.154919,72.843566,2.0,2.0,2.0,NaN,New Property,1.0,Semi-Furnished,5.0,goregaon west,Flat,\n\n\n Ekta tri...,17424.242424
7,22900000.0,"Goregaon West, Mumbai, Best Nagar - Goregaon W...",968.0,19.147269,72.848351,3.0,3.0,NaN,NaN,New Property,1.0,Unfurnished,6.0,Near Ram Mandir railway station goregaon west,Flat,\n \n \n...,23657.024793
8,17000000.0,"Wadala East, Mumbai, Wadala, Mumbai - Harbour ...",820.0,19.015128,72.858064,2.0,2.0,NaN,NaN,New Property,1.0,Unfurnished,3.0,Dosti acres.,Flat,\n\n\n PreLaunc...,20731.707317
9,81000000.0,"Worli, Mumbai, Worli, Mumbai - South Mumbai, M...",3260.0,19.001640,72.826532,3.0,3.0,3.0,Ready to Move,Resale,3.0,NaN,4.0,prime property,Flat,\n \n \n...,24846.625767
10,46000000.0,"near by nahur station, Mulund West, Mumbai - C...",2500.0,19.157602,72.945243,4.0,4.0,2.0,NaN,New Property,3.0,Unfurnished,4.0,near nahur station,Flat,\n \n \n...,18400.000000
11,34000000.0,"Mulund West, Mumbai, Mulund West, Mumbai - Cen...",1085.0,19.159575,72.946575,3.0,3.0,1.0,NaN,New Property,2.0,Unfurnished,3.0,Fortis Hospital,Flat,\n\n\n Presenti...,31336.405530
12,65000000.0,"Devle Rd, JVPD Scheme, Juhu, Mumbai, Maharasht...",1500.0,19.116129,72.821959,2.0,2.0,NaN,Ready to Move,Resale,2.0,NaN,2.0,Juhu,Flat,\n \n \n...,43333.333333
13,20300000.0,"Kanjurmarg West, Mumbai, Kanjurmarg West, Mumb...",891.0,18.924921,72.829722,3.0,3.0,1.0,NaN,New Property,1.0,Unfurnished,4.0,NaN,Flat,\n \n \n...,22783.389450
14,25000000.0,"Rajawadi, Ghatkopar east, Ghatkopar East, Mumb...",800.0,19.079070,72.907976,2.0,2.0,1.0,Ready to Move,Resale,NaN,NaN,NaN,Rajawadi derasar,Flat,\n \n \n...,31250.000000

In [4]:
df = df.rename(columns={
    'Bedrooms': 'bhk',
    'Bathrooms': 'bath',
    'Address': 'location'
})

In [5]:
df = df.rename(columns={
    'area': 'total_sqft',
})

In [6]:
df

,price,location,total_sqft,latitude,longitude,bhk,bath,Balcony,Status,neworold,parking,Furnished_status,Lift,Landmarks,type_of_building,desc,Price_sqft
0,22400000.0,"Chembur, Mumbai - Harbour Line, Maharashtra",629.0,19.032800,72.896357,2.0,2.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Right fr...,35612.082671
1,35000000.0,"Chembur, Mumbai - Harbour Line, Maharashtra",974.0,19.032800,72.896357,3.0,2.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Right fr...,35934.291581
2,31700000.0,"Ghatkopar East, Mumbai - Central Line, Maharas...",968.0,19.085600,72.909277,3.0,3.0,NaN,Under Construction,New Property,1.0,NaN,2.0,NaN,Flat,\n \n \n...,32747.933884
3,18700000.0,"Plot Number 283, Road Number 3, Jawahar Nagar,...",629.0,19.155756,72.846862,2.0,2.0,2.0,Ready to Move,New Property,1.0,NaN,3.0,Laxmi Callista,Flat,\n\n\n Welcome ...,29729.729730
4,13500000.0,"malad east, Malad East, Mumbai - North Mumbai,...",1090.0,19.177555,72.849887,2.0,2.0,NaN,NaN,New Property,1.0,Unfurnished,2.0,near uper govind nagar,Flat,\n \n \n...,12385.321101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6250,19500000.0,"Yari Road, Mumbai - Western Suburbs, Maharashtra",810.0,19.138320,72.810020,2.0,2.0,NaN,Ready to Move,Resale,1.0,Semi-Furnished,NaN,NaN,Flat,\n\n\n This Mu...,24074.074074
6251,22000000.0,"502., Hari Om Nagar, Mumbai - North Mumbai, Ma...",1400.0,19.221920,72.854250,3.0,3.0,1.0,Ready to Move,Resale,NaN,Unfurnished,NaN,NaN,Flat,\n \n \n...,15714.285714
6252,20000000.0,"Lokhandwala Complex, Andheri West, Lokhandwala...",750.0,19.144320,72.824111,2.0,2.0,NaN,Ready to Move,Resale,1.0,NaN,1.0,"Lokhandwala Complex, Andheri West",Flat,\n\n\n This Fr...,26666.666667
6253,11000000.0,"Sion, Mumbai - Central Mumbai, Maharashtra",700.0,19.047201,72.872225,2.0,2.0,NaN,Ready to Move,Resale,NaN,Furnished,NaN,NaN,Flat,\n,15714.285714
6254,15000000.0,"Mulund West, Mumbai - Central Line, Maharashtra",900.0,19.168818,72.936375,2.0,2.0,NaN,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n,16666.666667

In [7]:
df = df[['total_sqft', 'bhk', 'bath', 'location', 'price']]

In [8]:
df

,total_sqft,bhk,bath,location,price
0,629.0,2.0,2.0,"Chembur, Mumbai - Harbour Line, Maharashtra",22400000.0
1,974.0,3.0,2.0,"Chembur, Mumbai - Harbour Line, Maharashtra",35000000.0
2,968.0,3.0,3.0,"Ghatkopar East, Mumbai - Central Line, Maharas...",31700000.0
3,629.0,2.0,2.0,"Plot Number 283, Road Number 3, Jawahar Nagar,...",18700000.0
4,1090.0,2.0,2.0,"malad east, Malad East, Mumbai - North Mumbai,...",13500000.0
...,...,...,...,...,...
6250,810.0,2.0,2.0,"Yari Road, Mumbai - Western Suburbs, Maharashtra",19500000.0
6251,1400.0,3.0,3.0,"502., Hari Om Nagar, Mumbai - North Mumbai, Ma...",22000000.0
6252,750.0,2.0,2.0,"Lokhandwala Complex, Andheri West, Lokhandwala...",20000000.0
6253,700.0,2.0,2.0,"Sion, Mumbai - Central Mumbai, Maharashtra",11000000.0
6254,900.0,2.0,2.0,"Mulund West, Mumbai - Central Line, Maharashtra",15000000.0

In [9]:
df.location.unique()

<StringArray>
[                                                                                                                         'Chembur, Mumbai - Harbour Line, Maharashtra',
                                                                                                                   'Ghatkopar East, Mumbai - Central Line, Maharashtra',
 'Plot Number 283, Road Number 3, Jawahar Nagar, Off S. V. Road, Goregaon (West), Mumbai, Maharashtra, India 400104, Goregaon West, Mumbai - North Mumbai, Maharashtra',
                                                                                                           'malad east, Malad East, Mumbai - North Mumbai, Maharashtra',
                                                                                                         'Bhandup, Mumbai, Bhandup, Mumbai - Central Line, Maharashtra',
                                                                            'Siddharth Nagar, Goregaon West, Mumbai, Goregaon West, Mumbai - North Mumbai, Maharashtra',
                                                                                'Goregaon West, Mumbai, Best Nagar - Goregaon West, Mumbai - North Mumbai, Maharashtra',
                                                                                                      'Wadala East, Mumbai, Wadala, Mumbai - Harbour Line, Maharashtra',
                                                                                                             'Worli, Mumbai, Worli, Mumbai - South Mumbai, Maharashtra',
                                                                                               'near by nahur station, Mulund West, Mumbai - Central Line, Maharashtra',
 ...
                                                                                                          '6th Floor, Marine Drive, Mumbai - South Mumbai, Maharashtra',
                                                                                                                      'Opera House, Mumbai - South Mumbai, Maharashtra',
                                                                                                      'New Lotus CoOp, Mulund West, Mumbai - Central Line, Maharashtra',
                                                                                                'Shanti Nagar -  Mira Road, Mumbai - Mira Road and Beyond, Maharashtra',
                                                                                                'palat rod, Chedda Nagar - Chembur, Mumbai - Harbour Line, Maharashtra',
                                                                 'Mount Everest, Bhakti Park, Wadala East, Mumbai-37., Bhakti Park, Mumbai - Harbour Line, Maharashtra',
                                        '201, Nandkumar CHS, Nandapatkar Road, Vile-Parle(East), Mumbai-400057, Vile Parle East, Mumbai - Western Suburbs, Maharashtra',
                                  'bldg no-137, axiom aven, near ganesh mandir, pant nagar, ghatkopar-east, mum-75, Ghatkopar East, Mumbai - Central Line, Maharashtra',
                                                                                                              '502., Hari Om Nagar, Mumbai - North Mumbai, Maharashtra',
                                                                        'Lokhandwala Complex, Andheri West, Lokhandwala Complex, Mumbai - Western Suburbs, Maharashtra']
Length: 3632, dtype: str

In [10]:
import re

def extract_locality(address):
    if pd.isna(address):
        return None

    address = str(address).strip()

    # Look for the locality immediately before "Mumbai - ..."
    match = re.search(r',\s*([^,]+),\s*Mumbai\s*-', address, flags=re.IGNORECASE)

    if match:
        return match.group(1).strip()

    return address.split(',')[0].strip()

In [11]:
df['location'] = df['location'].apply(extract_locality)

In [12]:
df[['location']].head(20)

                      location
0                      Chembur
1                      Chembur
2               Ghatkopar East
3                Goregaon West
4                   Malad East
5                      Bhandup
6                Goregaon West
7   Best Nagar - Goregaon West
8                       Wadala
9                        Worli
10                 Mulund West
11                 Mulund West
12                        Juhu
13             Kanjurmarg West
14              Ghatkopar East
15             Kanjurmarg East
16                 Bandra East
17               Borivali West
18                 Mulund West
19                 Mulund West

In [13]:
df['location'].nunique()

752

In [14]:
df['location'].value_counts().head(50)

location
Mira Road                     311
Andheri West                  287
Mulund West                   192
Andheri East                  185
Chembur                       165
Kandivali West                164
Malad West                    149
Borivali West                 136
Goregaon West                 125
Virar West                    122
Goregaon East                 116
Kandivali East                116
Bhandup West                   93
Malad East                     92
Ghatkopar West                 88
Powai                          85
Worli                          70
Ghatkopar East                 68
Santacruz West                 68
Vile Parle East                66
Borivali East                  63
Parel                          61
Vasai West                     59
Dahisar East                   57
Virar                          54
Mulund East                    52
Vasai East                     51
Kalyan                         50
Khar West                      49
Chandivali                     45
Bandra West                    45
Ulhasnagar                     42
Santacruz East                 41
Juhu                           38
Marol                          38
Thakur Village                 38
Prabhadevi                     35
Mira Bhayandar                 34
Bhayandar West                 34
Wadala                         32
Vile Parle West                32
Kanjurmarg East                31
Tilak Nagar - Harbour Line     30
Lokhandwala Complex            30
Sion                           30
Vasai                          29
Bhayandar East                 28
Dadar West                     27
Bandra East                    26
Nalasopara West                25
Name: count, dtype: int64

In [15]:
df['location'].value_counts().describe()

count    752.000000
mean       8.317819
std       25.142445
min        1.000000
25%        1.000000
50%        1.000000
75%        5.000000
max      311.000000
Name: count, dtype: float64

In [16]:
df['location'].value_counts().tail(50)

location
Chikoowadi                                                                                    1
Postal Colony                                                                                 1
Kshitij L Jagmohandas Marg Neapeansea Road Malabar Hill Mumbai Maharashtra 400006             1
mulund west                                                                                   1
Jain Chowk                                                                                    1
Gandhi Market                                                                                 1
Azad Nagar Colaba                                                                             1
Ashok Nagar Saki Naka                                                                         1
Laxmi Narayan Temple Compound                                                                 1
Swami Jairamdas Cooperative Housing Society Ltd R C Marg Chembur Mumbai Maharashtra 400074    1
Hendre Mansion                                                                                1
Sarvodaya Nagar                                                                               1
Kandivali                                                                                     1
Suresh Colony                                                                                 1
MIRA ROAD-East                                                                                1
New Marine Lines                                                                              1
IC colony Borivali (w)                                                                        1
Prathmesh Aashish CHS LTD                                                                     1
Mulund Railway Station                                                                        1
Netaji Nagar                                                                                  1
Jaishastri Nagar                                                                              1
Lakeside                                                                                      1
Marol Naka Junction                                                                           1
Gaurav manthan society                                                                        1
Kastur Park                                                                                   1
Tata Housing Colony                                                                           1
Basant Cinema                                                                                 1
Bandra Band Stand                                                                             1
Samel Pada                                                                                    1
Chandan Shanti                                                                                1
Ambernath west                                                                                1
Turner Road                                                                                   1
Nai Gaon                                                                                      1
Churi Wadi                                                                                    1
Naya Nagar                                                                                    1
Koldongri                                                                                     1
Oslo 1201                                                                                     1
Koliwada                                                                                      1
new saichartan darshan D/202.bhayender eas                                                    1
Tilak Nagar                                                                                   1
Mandir Chowk                                                                                  1
K C Pavanputr residencyR1/201Kalehar Bhiwandi                                                 1
Ekta Nagar Charkop                                                                            1
Mumbai CST Area                                                                               1
MIG Colony                                                                                    1
Kala Ghoda                                                                                    1
Bhuleshwar Market                                                                             1
Shanti Nagar -  Mira Road                                                                     1
Vile-Parle(East)                                                                              1
Hari Om Nagar                                                                                 1
Name: count, dtype: int64

In [17]:
location_counts = df['location'].value_counts()

df['location'] = df['location'].apply(
    lambda x: x if location_counts[x] >= 10 else 'Other'
)

In [18]:
df['location'].value_counts().tail(20)

location
Sector 8 Charkop                      12
Lokhandwala Twp                       11
Chembur East                          11
Bandra Kurla Complex                  11
Deonar                                11
Jogeshwari East                       11
Thakur Complex                        11
Mumbai Central                        11
Pali Hill                             11
Malabar Hill                          11
Sindhi Society Chembur                11
Walkeshwar                            11
Nalasopara East                       11
Dahanukar Wadi                        11
Grant Road                            11
JVLR-Jogeshwari Vikhroli Link Road    10
Yari Road                             10
Cuffe Parade                          10
Malvani                               10
Link Road                             10
Name: count, dtype: int64

In [19]:
df['location'].nunique()

115

In [20]:
df['location'].value_counts().head(10)

location
Other             1364
Mira Road          311
Andheri West       287
Mulund West        192
Andheri East       185
Chembur            165
Kandivali West     164
Malad West         149
Borivali West      136
Goregaon West      125
Name: count, dtype: int64

In [21]:
df.head(40)

    total_sqft  bhk  bath         location        price
0        629.0  2.0   2.0          Chembur   22400000.0
1        974.0  3.0   2.0          Chembur   35000000.0
2        968.0  3.0   3.0   Ghatkopar East   31700000.0
3        629.0  2.0   2.0    Goregaon West   18700000.0
4       1090.0  2.0   2.0       Malad East   13500000.0
5        630.0  2.0   2.0          Bhandup   13000000.0
6       1188.0  2.0   2.0    Goregaon West   20700000.0
7        968.0  3.0   3.0            Other   22900000.0
8        820.0  2.0   2.0           Wadala   17000000.0
9       3260.0  3.0   3.0            Worli   81000000.0
10      2500.0  4.0   4.0      Mulund West   46000000.0
11      1085.0  3.0   3.0      Mulund West   34000000.0
12      1500.0  2.0   2.0             Juhu   65000000.0
13       891.0  3.0   3.0  Kanjurmarg West   20300000.0
14       800.0  2.0   2.0   Ghatkopar East   25000000.0
15      1020.0  3.0   3.0  Kanjurmarg East   21000000.0
16      3180.0  4.0   4.0      Bandra East  102000000.0
17      1000.0  3.0   3.0    Borivali West   22500000.0
18      1058.0  2.0   2.0      Mulund West   19000000.0
19       875.0  2.0   2.0      Mulund West   15500000.0
20      1500.0  3.0   3.0   Ghatkopar West   25000000.0
21      1600.0  3.0   3.0      Mulund West   22500000.0
22      2430.0  4.0   4.0    Goregaon East   55000000.0
23       688.0  2.0   2.0      Mulund West   15000000.0
24       950.0  2.0   2.0     Andheri West   23900000.0
25       900.0  2.0   2.0            Other   25000000.0
26      2135.0  4.0   5.0            Worli   69000000.0
27      1412.0  3.0   3.0            Other    9750000.0
28      1450.0  3.0   3.0            Other   25500000.0
29      1765.0  3.0   2.0            Parel   39800000.0
30      1818.0  3.0   3.0            Other   47500000.0
31      1355.0  3.0   3.0            Other   34000000.0
32      1415.0  3.0   3.0      Mulund West   46300000.0
33      1045.0  2.0   2.0            Other    8600000.0
34       965.0  2.0   2.0            Other   20000000.0
35      2560.0  3.0   3.0      Mulund West   33500000.0
36      1500.0  3.0   3.0            Worli   62500000.0
37      2195.0  3.0   4.0    Goregaon East   47000000.0
38      1175.0  2.0   2.0          Chembur   18500000.0
39       983.0  2.0   2.0           Wadala   28000000.0

In [22]:
df.isnull().sum()

total_sqft    0
bhk           0
bath          0
location      0
price         0
dtype: int64

In [23]:
df[['total_sqft', 'bhk', 'bath', 'price']].describe()

        total_sqft          bhk         bath         price
count  6255.000000  6255.000000  6255.000000  6.255000e+03
mean   1185.625260     2.452278     2.425580  2.684187e+07
std     636.973259     0.749534     0.762604  2.788831e+07
min     503.000000     2.000000     0.000000  1.500000e+06
25%     846.500000     2.000000     2.000000  1.300000e+07
50%    1000.000000     2.000000     2.000000  1.900000e+07
75%    1300.000000     3.000000     3.000000  3.000000e+07
max    8000.000000    10.000000    10.000000  3.600000e+08

In [24]:
df[df['bath'] == 0]

      total_sqft  bhk  bath        location       price
3021       812.0  2.0   0.0  Kandivali West  12000000.0

In [25]:
df['bath'].value_counts().sort_index()

bath
0.0        1
2.0     4335
3.0     1387
4.0      382
5.0      106
6.0       33
7.0        5
8.0        5
10.0       1
Name: count, dtype: int64

In [26]:
df = df[df['bath'] > 0]

In [27]:
df[df['bath'] >= 10]

      total_sqft   bhk  bath location       price
2994       816.0  10.0  10.0    Other  80000000.0

In [28]:
df.groupby('bhk')['bath'].agg(['min', 'max', 'mean', 'count'])

      min   max      mean  count
bhk
2.0   2.0   4.0  2.043457   4096
3.0   2.0   6.0  2.860979   1676
4.0   2.0   8.0  3.975275    364
5.0   2.0   6.0  4.486842     76
6.0   2.0   7.0  4.846154     26
7.0   2.0   8.0  5.333333      9
8.0   2.0   8.0  5.750000      4
10.0  4.0  10.0  7.333333      3

In [29]:
df['sqft_per_bhk'] = df['total_sqft'] / df['bhk']

df['sqft_per_bhk'].describe()

count    6254.000000
mean      475.864642
std       151.816805
min        81.600000
25%       389.125000
50%       450.000000
75%       533.333333
max      3000.000000
Name: sqft_per_bhk, dtype: float64

In [30]:
df[df['sqft_per_bhk'] < 250].sort_values('sqft_per_bhk').head(20)

      total_sqft   bhk  bath        location       price  sqft_per_bhk
2994       816.0  10.0  10.0           Other  80000000.0     81.600000
957        660.0   6.0   2.0           Other  10500000.0    110.000000
3084      1200.0   8.0   8.0      Ulhasnagar   9000000.0    150.000000
6213       600.0   4.0   3.0      Vasai West   6000000.0    150.000000
2638       516.0   3.0   3.0     Mulund West  15000000.0    172.000000
1186       570.0   3.0   2.0    Dahisar East  12500000.0    190.000000
3426       600.0   3.0   4.0           Other   8000000.0    200.000000
3602      1000.0   5.0   5.0         Chembur  19000000.0    200.000000
2596       600.0   3.0   2.0          Vakola   4500000.0    200.000000
5978       600.0   3.0   3.0    Andheri West   8000000.0    200.000000
1997       600.0   3.0   3.0           Other  20000000.0    200.000000
5878       600.0   3.0   2.0            Sion   6500000.0    200.000000
1470       600.0   3.0   2.0           Other  35000000.0    200.000000
6144       620.0   3.0   3.0           Other   2600000.0    206.666667
5103       625.0   3.0   3.0  Kandivali East  26000000.0    208.333333
5460      1500.0   7.0   6.0         Gorai 2  25000000.0    214.285714
3915       650.0   3.0   3.0      Virar West   3000000.0    216.666667
3031      1100.0   5.0   5.0           Other  40000000.0    220.000000
2587       672.0   3.0   3.0     Mulund East  16000000.0    224.000000
1449       673.0   3.0   3.0        Oshiwara  22500000.0    224.333333

In [31]:
(df['sqft_per_bhk'] < 200).sum(), (df['sqft_per_bhk'] < 250).sum(), (df['sqft_per_bhk'] < 300).sum()

(np.int64(6), np.int64(43), np.int64(263))

In [32]:
df[df['sqft_per_bhk'] < 200].sort_values('sqft_per_bhk')

      total_sqft   bhk  bath      location       price  sqft_per_bhk
2994       816.0  10.0  10.0         Other  80000000.0          81.6
957        660.0   6.0   2.0         Other  10500000.0         110.0
3084      1200.0   8.0   8.0    Ulhasnagar   9000000.0         150.0
6213       600.0   4.0   3.0    Vasai West   6000000.0         150.0
2638       516.0   3.0   3.0   Mulund West  15000000.0         172.0
1186       570.0   3.0   2.0  Dahisar East  12500000.0         190.0

In [33]:
df = df[df['sqft_per_bhk'] >= 200]

In [34]:
df = df.drop(columns='sqft_per_bhk')

In [35]:
df[['total_sqft', 'bhk', 'bath', 'price']].describe()

        total_sqft          bhk         bath         price
count  6248.000000  6248.000000  6248.000000  6.248000e+03
mean   1186.125480     2.449264     2.423816  2.684874e+07
std     637.113414     0.738816     0.752961  2.789127e+07
min     503.000000     2.000000     2.000000  1.500000e+06
25%     848.000000     2.000000     2.000000  1.300000e+07
50%    1000.000000     2.000000     2.000000  1.900000e+07
75%    1300.000000     3.000000     3.000000  3.000000e+07
max    8000.000000    10.000000     8.000000  3.600000e+08

In [36]:
df.sort_values('price').head(10)

      total_sqft  bhk  bath      location      price
3566      1000.0  3.0   2.0    Kurla West  1500000.0
4838       580.0  2.0   2.0     Ambernath  1650000.0
4357       700.0  2.0   2.0    Ulhasnagar  1700000.0
4426       695.0  2.0   2.0  Dahisar East  2000000.0
6212       600.0  2.0   2.0    Virar East  2200000.0
6122       800.0  2.0   2.0         Other  2200000.0
1298       528.0  2.0   2.0        Kalyan  2400000.0
1500       535.0  2.0   2.0        Kalyan  2400000.0
5552       645.0  2.0   3.0       Chembur  2500000.0
5919       740.0  2.0   2.0         Virar  2500000.0

In [37]:
df['price_per_sqft'] = df['price'] / df['total_sqft']

In [38]:
df.sort_values('price', ascending=False).head(20)

      total_sqft   bhk  bath      location        price  price_per_sqft
5937      6100.0   4.0   8.0         Other  360000000.0    59016.393443
6237      8000.0   5.0   6.0         Other  350000000.0    43750.000000
94        8000.0   5.0   6.0         Worli  340000000.0    42500.000000
1453      6600.0   5.0   4.0   Lower Parel  340000000.0    51515.151515
3822      3500.0  10.0   8.0    Mahim West  340000000.0    97142.857143
1743      4122.0   5.0   6.0         Other  300000000.0    72780.203785
746       3150.0   4.0   5.0    Walkeshwar  300000000.0    95238.095238
4308      7500.0   4.0   4.0         Other  270000000.0    36000.000000
566       3000.0   4.0   5.0  Cuffe Parade  265000000.0    88333.333333
2389      6900.0   5.0   6.0   Lower Parel  260000000.0    37681.159420
5998      2300.0   4.0   4.0  Cuffe Parade  260000000.0   113043.478261
1087      2546.0   4.0   5.0   Bandra West  250000000.0    98193.244305
3254      2100.0   4.0   4.0          Sion  250000000.0   119047.619048
3873      4500.0   5.0   5.0         Other  250000000.0    55555.555556
4848      4000.0   4.0   7.0         Other  250000000.0    62500.000000
824       7500.0   7.0   8.0         Other  250000000.0    33333.333333
306       2555.0   3.0   3.0         Other  230000000.0    90019.569472
101       4600.0   4.0   4.0         Other  230000000.0    50000.000000
2398      3000.0   4.0   4.0    Walkeshwar  220000000.0    73333.333333
4285      2810.0   4.0   5.0         Worli  220000000.0    78291.814947

In [39]:
df['price_per_sqft'].describe()

count      6248.000000
mean      21415.358659
std       12665.665312
min        1500.000000
25%       13712.110225
50%       19285.714286
75%       26500.000000
max      119047.619048
Name: price_per_sqft, dtype: float64

In [40]:
location_stats = df.groupby('location')['price_per_sqft'].agg(
    ['mean', 'std', 'count']
)

location_stats.sort_values('mean', ascending=False).head(20)

                         mean           std  count
location
Cuffe Parade     69470.784213  19719.744076     10
Napean Sea Road  69290.389019  20280.194542     15
Walkeshwar       69062.811075  12740.814363     11
Malabar Hill     63098.919528  18353.825295     11
Bandra West      51991.002325  19538.716823     45
Pali Hill        51323.495457  13416.366031     11
JVPD Scheme      43529.961059  13096.342018     16
Tardeo           42972.205200  10511.495780     14
Juhu             42878.155044  14333.567434     38
Khar West        41194.555955   9680.172764     49
Worli            39065.538429  11747.271936     70
Matunga East     37933.179170   6434.654164     20
Santacruz West   37030.208023  10287.950505     68
Lower Parel      36944.812618   8304.659095     15
Matunga West     36521.874703  11415.811464     13
Mahim West       36109.484751  15525.209216     22
Prabhadevi       35773.006788   6444.320862     35
Dadar East       35716.259072   7656.342509     22
Agripada         35628.942263   8720.286716     15
Vile Parle West  35619.259059   8768.484632     32

In [41]:
location_stats = df.groupby('location')['price_per_sqft'].agg(['mean', 'std', 'count'])

df['location_mean'] = df['location'].map(location_stats['mean'])
df['location_std'] = df['location'].map(location_stats['std'])

df['location_zscore'] = (
    (df['price_per_sqft'] - df['location_mean'])
    / df['location_std']
)

In [42]:
(df['location_zscore'].abs() > 2).sum()

np.int64(286)

In [43]:
df[df['location_zscore'].abs() > 2].sort_values(
    'location_zscore',
    key=abs,
    ascending=False
).head(30)

,total_sqft,bhk,bath,location,price,price_per_sqft,location_mean,location_std,location_zscore
3257,2000.0,4.0,4.0,Chembur,170000000.0,85000.000000,22987.406799,8238.207424,7.527438
3833,1380.0,4.0,4.0,Goregaon East,100000000.0,72463.768116,19028.305111,8640.481635,6.184315
2625,2000.0,4.0,3.0,Other,200000000.0,100000.000000,22330.346510,13651.284938,5.689549
2194,1000.0,2.0,2.0,Mira Road,20000000.0,20000.000000,9584.106188,1953.036211,5.333180
306,2555.0,3.0,3.0,Other,230000000.0,90019.569472,22330.346510,13651.284938,4.958451
484,1500.0,2.0,3.0,Other,130000000.0,86666.666667,22330.346510,13651.284938,4.712840
5734,2100.0,4.0,4.0,Other,180000000.0,85714.285714,22330.346510,13651.284938,4.643075
5103,625.0,3.0,3.0,Kandivali East,26000000.0,41600.000000,18486.247664,5048.064959,4.578735
3254,2100.0,4.0,4.0,Sion,250000000.0,119047.619048,30888.032616,19323.253989,4.562357
1012,604.0,2.0,2.0,Virar West,7500000.0,12417.218543,5599.668230,1507.543001,4.522292
3055,750.0,2.0,2.0,Bhayandar West,22200000.0,29600.000000,10617.752841,4242.374606,4.474439
2888,1150.0,2.0,2.0,Other,95000000.0,82608.695652,22330.346510,13651.284938,4.415581
2431,1000.0,3.0,3.0,Other,82500000.0,82500.000000,22330.346510,13651.284938,4.407618
3615,1155.0,3.0,3.0,Andheri West,65000000.0,56277.056277,25778.455189,6961.324699,4.381149
6061,1830.0,3.0,4.0,Other,150000000.0,81967.213115,22330.346510,13651.284938,4.368590
5983,1650.0,3.0,3.0,Other,135000000.0,81818.181818,22330.346510,13651.284938,4.357673
1563,1385.0,3.0,2.0,Mira Road,25000000.0,18050.541516,9584.106188,1953.036211,4.335012
595,800.0,3.0,4.0,Goregaon East,45000000.0,56250.000000,19028.305111,8640.481635,4.307826
2539,1850.0,3.0,4.0,Other,150000000.0,81081.081081,22330.346510,13651.284938,4.303678
360,638.0,2.0,2.0,Bhandup West,20000000.0,31347.962382,16420.312739,3469.046260,4.303099
4760,1783.0,4.0,4.0,Vile Parle East,115000000.0,64498.037016,31962.481354,7669.834334,4.242015
1920,835.0,2.0,2.0,Bhayandar East,19000000.0,22754.491018,9730.695927,3079.783636,4.228802
3303,4500.0,6.0,7.0,Kandivali West,180000000.0,40000.000000,18482.486619,5233.695021,4.111343
2731,1500.0,3.0,3.0,Other,115000000.0,76666.666667,22330.346510,13651.284938,3.980308
2759,850.0,2.0,2.0,Other,65000000.0,76470.588235,22330.346510,13651.284938,3.965945
3822,3500.0,10.0,8.0,Mahim West,340000000.0,97142.857143,36109.484751,15525.209216,3.931243
869,1200.0,3.0,2.0,Other,90000000.0,75000.000000,22330.346510,13651.284938,3.858219
6151,1000.0,3.0,2.0,Vasai West,14000000.0,14000.000000,6968.736530,1837.132453,3.827304
3524,1050.0,2.0,3.0,Other,78000000.0,74285.714286,22330.346510,13651.284938,3.805896
2555,1080.0,2.0,2.0,Other,80000000.0,74074.074074,22330.346510,13651.284938,3.790392

In [44]:
(df['location_zscore'].abs() > 3).sum()

np.int64(68)

In [45]:
df[df['location_zscore'].abs() > 3].sort_values(
    'location_zscore',
    key=abs,
    ascending=False
)

,total_sqft,bhk,bath,location,price,price_per_sqft,location_mean,location_std,location_zscore
3257,2000.0,4.0,4.0,Chembur,170000000.0,85000.000000,22987.406799,8238.207424,7.527438
3833,1380.0,4.0,4.0,Goregaon East,100000000.0,72463.768116,19028.305111,8640.481635,6.184315
2625,2000.0,4.0,3.0,Other,200000000.0,100000.000000,22330.346510,13651.284938,5.689549
2194,1000.0,2.0,2.0,Mira Road,20000000.0,20000.000000,9584.106188,1953.036211,5.333180
306,2555.0,3.0,3.0,Other,230000000.0,90019.569472,22330.346510,13651.284938,4.958451
...,...,...,...,...,...,...,...,...,...
1218,750.0,2.0,2.0,Other,48500000.0,64666.666667,22330.346510,13651.284938,3.101270
1084,1414.0,3.0,4.0,Vasai,14500000.0,10254.596888,6312.100263,1274.934427,3.092313
1637,5500.0,2.0,2.0,Ghatkopar East,13000000.0,2363.636364,25314.379524,7475.199629,-3.070252
2530,1000.0,3.0,3.0,Mulund West,35000000.0,35000.000000,19449.554213,5065.242813,3.070030
3261,700.0,2.0,2.0,Malad East,25000000.0,35714.285714,19736.482550,5256.438722,3.039663

In [46]:
df = df.drop(columns=[
    'price_per_sqft',
    'location_mean',
    'location_std',
    'location_zscore'
])

In [47]:
df.shape

(6248, 5)

In [48]:
df.duplicated().sum()

np.int64(222)

In [49]:
df[df.duplicated(keep=False)].sort_values(
    ['total_sqft', 'bhk', 'bath', 'location', 'price']
).head(20)

      total_sqft  bhk  bath       location       price
1539       510.0  2.0   2.0          Worli  27500000.0
4495       510.0  2.0   2.0          Worli  27500000.0
853        535.0  2.0   2.0     Malad West  11000000.0
1653       535.0  2.0   2.0     Malad West  11000000.0
2285       535.0  2.0   2.0     Malad West  11000000.0
864        550.0  2.0   2.0   Andheri West  17000000.0
1559       550.0  2.0   2.0   Andheri West  17000000.0
1656       600.0  2.0   2.0  Borivali West  15000000.0
2753       600.0  2.0   2.0  Borivali West  15000000.0
1975       600.0  2.0   2.0          Other   6500000.0
5760       600.0  2.0   2.0          Other   6500000.0
1155       650.0  2.0   2.0         Kalina  12500000.0
1916       650.0  2.0   2.0         Kalina  12500000.0
3623       650.0  2.0   2.0          Other   9500000.0
5305       650.0  2.0   2.0          Other   9500000.0
1195       650.0  2.0   2.0          Other  17000000.0
1678       650.0  2.0   2.0          Other  17000000.0
1699       675.0  2.0   2.0          Other  12500000.0
5804       675.0  2.0   2.0          Other  12500000.0
2076       680.0  2.0   2.0          Other  15000000.0

In [50]:
df = df.drop_duplicates()

In [51]:
df.shape

(6026, 5)

In [52]:
df.info()

<class 'pandas.DataFrame'>
Index: 6026 entries, 0 to 6254
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_sqft  6026 non-null   float64
 1   bhk         6026 non-null   float64
 2   bath        6026 non-null   float64
 3   location    6026 non-null   str
 4   price       6026 non-null   float64
dtypes: float64(4), str(1)
memory usage: 282.5 KB

In [53]:
df.head()

   total_sqft  bhk  bath        location       price
0       629.0  2.0   2.0         Chembur  22400000.0
1       974.0  3.0   2.0         Chembur  35000000.0
2       968.0  3.0   3.0  Ghatkopar East  31700000.0
3       629.0  2.0   2.0   Goregaon West  18700000.0
4      1090.0  2.0   2.0      Malad East  13500000.0

In [54]:
df.sort_values('total_sqft').head(15)

      total_sqft  bhk  bath         location       price
2172       503.0  2.0   2.0       Virar West   4000000.0
4859       506.0  2.0   3.0            Other  18500000.0
2681       506.0  2.0   3.0            Parel  18500000.0
3842       507.0  2.0   2.0            Other  15000000.0
1539       510.0  2.0   2.0            Worli  27500000.0
2815       510.0  2.0   2.0            Other  12500000.0
5162       510.0  2.0   2.0     Andheri West  15000000.0
3308       510.0  2.0   2.0          Chembur  12500000.0
3495       510.0  2.0   2.0            Other  16000000.0
4941       510.0  2.0   2.0   Kandivali West  12000000.0
1480       520.0  2.0   2.0   Kandivali West   9500000.0
6236       520.0  2.0   2.0  Vile Parle West  17500000.0
6125       520.0  2.0   2.0            Other   6500000.0
1263       520.0  2.0   2.0  Vile Parle West  17000000.0
2859       520.0  2.0   2.0     Andheri West  11500000.0

In [55]:
df.sort_values('total_sqft', ascending=False).head(15)

      total_sqft  bhk  bath        location        price
2841      8000.0  4.0   6.0  Ghatkopar West  100000000.0
6237      8000.0  5.0   6.0           Other  350000000.0
94        8000.0  5.0   6.0           Worli  340000000.0
824       7500.0  7.0   8.0           Other  250000000.0
4308      7500.0  4.0   4.0           Other  270000000.0
2389      6900.0  5.0   6.0     Lower Parel  260000000.0
1649      6712.0  7.0   7.0       Link Road  150000000.0
1453      6600.0  5.0   4.0     Lower Parel  340000000.0
403       6200.0  5.0   6.0     Bandra West  210000000.0
5937      6100.0  4.0   8.0           Other  360000000.0
1035      6000.0  2.0   2.0  Mumbai Central   23000000.0
3009      6000.0  6.0   5.0      Vasai West   55000000.0
2686      5800.0  3.0   2.0   Goregaon West   63000000.0
2982      5640.0  6.0   3.0           Other   80000000.0
1965      5500.0  2.0   2.0      Vasai East   22000000.0

In [56]:
df[df['bath'] > df['bhk'] + 2].sort_values(
    ['bhk', 'bath']
)

      total_sqft  bhk  bath    location        price
1890      2205.0  3.0   6.0  Ulhasnagar   13000000.0
4848      4000.0  4.0   7.0       Other  250000000.0
5937      6100.0  4.0   8.0       Other  360000000.0

In [57]:
df['sqft_per_bhk'] = df['total_sqft'] / df['bhk']

df.sort_values('sqft_per_bhk', ascending=False).head(20)

      total_sqft  bhk  bath        location        price  sqft_per_bhk
1035      6000.0  2.0   2.0  Mumbai Central   23000000.0   3000.000000
1965      5500.0  2.0   2.0      Vasai East   22000000.0   2750.000000
1637      5500.0  2.0   2.0  Ghatkopar East   13000000.0   2750.000000
1993      4500.0  2.0   2.0    Andheri West  130000000.0   2250.000000
2841      8000.0  4.0   6.0  Ghatkopar West  100000000.0   2000.000000
1782      3889.0  2.0   2.0           Other   62700000.0   1944.500000
2686      5800.0  3.0   2.0   Goregaon West   63000000.0   1933.333333
4308      7500.0  4.0   4.0           Other  270000000.0   1875.000000
1073      3500.0  2.0   3.0      Virar East   14000000.0   1750.000000
6237      8000.0  5.0   6.0           Other  350000000.0   1600.000000
94        8000.0  5.0   6.0           Worli  340000000.0   1600.000000
5220      4678.0  3.0   3.0     Lower Parel  160000000.0   1559.333333
5937      6100.0  4.0   8.0           Other  360000000.0   1525.000000
2149      3000.0  2.0   2.0      Vasai West   12000000.0   1500.000000
830       4500.0  3.0   2.0           Other  120000000.0   1500.000000
5987      4500.0  3.0   3.0           Other   30000000.0   1500.000000
5255      2900.0  2.0   2.0           Parel   39500000.0   1450.000000
2389      6900.0  5.0   6.0     Lower Parel  260000000.0   1380.000000
3530      5500.0  4.0   2.0           Other   50000000.0   1375.000000
1878      2700.0  2.0   2.0         Bhandup   30000000.0   1350.000000

In [58]:
(df['sqft_per_bhk'] > 1000).sum(), \
(df['sqft_per_bhk'] > 1500).sum(), \
(df['sqft_per_bhk'] > 2000).sum()

(np.int64(53), np.int64(13), np.int64(4))

In [59]:
df[df['sqft_per_bhk'] > 2000].sort_values(
    'sqft_per_bhk',
    ascending=False
)

      total_sqft  bhk  bath        location        price  sqft_per_bhk
1035      6000.0  2.0   2.0  Mumbai Central   23000000.0        3000.0
1637      5500.0  2.0   2.0  Ghatkopar East   13000000.0        2750.0
1965      5500.0  2.0   2.0      Vasai East   22000000.0        2750.0
1993      4500.0  2.0   2.0    Andheri West  130000000.0        2250.0

In [60]:
df['bhk'].value_counts().sort_index()

bhk
2.0     3911
3.0     1638
4.0      362
5.0       76
6.0       25
7.0        9
8.0        3
10.0       2
Name: count, dtype: int64

In [61]:
df[df['bhk'] >= 7].sort_values('bhk')

      total_sqft   bhk  bath      location        price  sqft_per_bhk
404       5000.0   7.0   7.0     Pali Hill  165000000.0    714.285714
824       7500.0   7.0   8.0         Other  250000000.0   1071.428571
1044      3000.0   7.0   5.0         Other   90000000.0    428.571429
1648      1800.0   7.0   3.0         Other   24000000.0    257.142857
1649      6712.0   7.0   7.0     Link Road  150000000.0    958.857143
2047      3600.0   7.0   7.0     Sion East  105000000.0    514.285714
2642      2000.0   7.0   2.0         Other   35000000.0    285.714286
2795      4800.0   7.0   3.0  Dahisar West   90000000.0    685.714286
5460      1500.0   7.0   6.0       Gorai 2   25000000.0    214.285714
381       3600.0   8.0   5.0         Other  130000000.0    450.000000
603       3600.0   8.0   8.0        Mulund  120000000.0    450.000000
3289      2100.0   8.0   2.0         Other   30000000.0    262.500000
3517      5000.0  10.0   4.0    Ulhasnagar   45000000.0    500.000000
3822      3500.0  10.0   8.0    Mahim West  340000000.0    350.000000

In [62]:
df['price_per_sqft'] = df['price'] / df['total_sqft']

df.sort_values('price_per_sqft').head(20)

,total_sqft,bhk,bath,location,price,sqft_per_bhk,price_per_sqft
3566,1000.0,3.0,2.0,Kurla West,1500000.0,333.333333,1500.000000
5820,2550.0,3.0,3.0,Vasai West,4500000.0,850.000000,1764.705882
6067,2200.0,3.0,3.0,Vikhroli West,4000000.0,733.333333,1818.181818
1199,2000.0,5.0,5.0,Andheri West,4450000.0,400.000000,2225.000000
4776,1500.0,2.0,2.0,Kalyan,3500000.0,750.000000,2333.333333
4484,1270.0,2.0,2.0,Ulhasnagar,3000000.0,635.000000,2362.204724
1637,5500.0,2.0,2.0,Ghatkopar East,13000000.0,2750.000000,2363.636364
4357,700.0,2.0,2.0,Ulhasnagar,1700000.0,350.000000,2428.571429
5825,2150.0,2.0,3.0,Other,5800000.0,1075.000000,2697.674419
6122,800.0,2.0,2.0,Other,2200000.0,400.000000,2750.000000
4838,580.0,2.0,2.0,Ambernath,1650000.0,290.000000,2844.827586
4059,2613.0,3.0,3.0,Nalasopara West,7500000.0,871.000000,2870.264064
4426,695.0,2.0,2.0,Dahisar East,2000000.0,347.500000,2877.697842
2824,1000.0,2.0,2.0,Ulhasnagar,2880000.0,500.000000,2880.000000
4329,1100.0,2.0,2.0,Virar,3200000.0,550.000000,2909.090909
5647,1100.0,2.0,2.0,Ulhasnagar,3200000.0,550.000000,2909.090909
5847,1000.0,2.0,2.0,Ulhasnagar,2950000.0,500.000000,2950.000000
3584,900.0,2.0,2.0,Ulhasnagar,2700000.0,450.000000,3000.000000
5892,1000.0,2.0,2.0,Malad West,3000000.0,500.000000,3000.000000
5954,985.0,2.0,2.0,Ulhasnagar,3000000.0,492.500000,3045.685279

In [63]:
df[df['price_per_sqft'] < 2500].sort_values('price_per_sqft')

,total_sqft,bhk,bath,location,price,sqft_per_bhk,price_per_sqft
3566,1000.0,3.0,2.0,Kurla West,1500000.0,333.333333,1500.000000
5820,2550.0,3.0,3.0,Vasai West,4500000.0,850.000000,1764.705882
6067,2200.0,3.0,3.0,Vikhroli West,4000000.0,733.333333,1818.181818
1199,2000.0,5.0,5.0,Andheri West,4450000.0,400.000000,2225.000000
4776,1500.0,2.0,2.0,Kalyan,3500000.0,750.000000,2333.333333
4484,1270.0,2.0,2.0,Ulhasnagar,3000000.0,635.000000,2362.204724
1637,5500.0,2.0,2.0,Ghatkopar East,13000000.0,2750.000000,2363.636364
4357,700.0,2.0,2.0,Ulhasnagar,1700000.0,350.000000,2428.571429

In [64]:
(df['price_per_sqft'] < 2500).sum()

np.int64(8)

In [65]:
low_price = df[df['price_per_sqft'] < 2500].copy()

location_median = df.groupby('location')['price_per_sqft'].median()

low_price['location_median'] = low_price['location'].map(location_median)

low_price[['total_sqft', 'bhk', 'location',
           'price', 'price_per_sqft', 'location_median']]

,total_sqft,bhk,location,price,price_per_sqft,location_median
1199,2000.0,5.0,Andheri West,4450000.0,2225.000000,25000.000000
1637,5500.0,2.0,Ghatkopar East,13000000.0,2363.636364,25000.000000
3566,1000.0,3.0,Kurla West,1500000.0,1500.000000,17866.481439
4357,700.0,2.0,Ulhasnagar,1700000.0,2428.571429,5084.745763
4484,1270.0,2.0,Ulhasnagar,3000000.0,2362.204724,5084.745763
4776,1500.0,2.0,Kalyan,3500000.0,2333.333333,6329.131653
5820,2550.0,3.0,Vasai West,4500000.0,1764.705882,6858.552632
6067,2200.0,3.0,Vikhroli West,4000000.0,1818.181818,20353.323406

In [66]:
outliers = [1199, 1637, 3566, 6067]

df = df.drop(index=outliers)

In [67]:
df = df.drop(columns=['sqft_per_bhk', 'price_per_sqft'])

In [68]:
df.info()

<class 'pandas.DataFrame'>
Index: 6022 entries, 0 to 6254
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_sqft  6022 non-null   float64
 1   bhk         6022 non-null   float64
 2   bath        6022 non-null   float64
 3   location    6022 non-null   str
 4   price       6022 non-null   float64
dtypes: float64(4), str(1)
memory usage: 282.3 KB

In [69]:
df[df['location'] == 'Other']['price'].describe()

count    1.253000e+03
mean     2.956469e+07
std      3.282335e+07
min      2.200000e+06
25%      1.350000e+07
50%      2.000000e+07
75%      3.330000e+07
max      3.600000e+08
Name: price, dtype: float64

In [70]:
df['price'].describe()

count    6.022000e+03
mean     2.714129e+07
std      2.821948e+07
min      1.650000e+06
25%      1.300000e+07
50%      1.950000e+07
75%      3.000000e+07
max      3.600000e+08
Name: price, dtype: float64

In [71]:

df.shape
df.columns
df.isnull().sum()

total_sqft    0
bhk           0
bath          0
location      0
price         0
dtype: int64

In [72]:
df = pd.get_dummies(
    df,
    columns=['location'],
    prefix='location'
)

In [73]:
X = df.drop(columns=['price'])
y = df['price']

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=10
)

In [75]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [76]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 8374983.0449934695
RMSE: 15832715.196973355
R²  : 0.6691392893193557

In [77]:
import pickle
import json
import os

os.makedirs('../model/mumbai', exist_ok=True)

with open('../model/mumbai/mumbai_home_price_predictor.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('../model/mumbai/mumbai_columns.json', 'w') as f:
    json.dump(list(X.columns), f)

print("Mumbai model saved successfully!")

Mumbai model saved successfully!